<div class="background">
    <img class="banner" src="../images/background.webp" alt="french castle banner">
</div>
<div class="title">
    <h1>Royalement Français!</h1>
    <h2>« A nul autre pareil ! »</h2>
</div>
</header>


<main class="main-profil">

    <form action="" method="POST">
        <button type="submit" name="logout">Déconnexion</button>
    </form>

</main>

<div class="orders-list">
    <h3>Vos commandes récentes</h3>
    <!-- boucle for each qui affichera les 3 dernières commandes -->
</div>

<div class="personal">
    <div>
        <h3>Informations personnelles <a href="/modifyProfil">🖉</a></h3>

    </div>

    <br>
    <?= '<p> Nom : ' . $_SESSION['user_name'] . '</p>' ?>
    <br>
    <?= '<p> Prénom : ' . $_SESSION['user_firstname'] . '</p>' ?>
    <br>
    <?= '<p>Mail : ' . $_SESSION['email'] . '</p>' ?>
    <br>
    <?php
        $explode = $_SESSION['userBirthday'];
        $number = explode("-", $explode);
        $date = new DateTime();
        $date->setDate($number[0], $number[1],$number[2]);
        $birthday = $date->format('d/m/Y');
        echo '<p> date de naissance : ' . $birthday . '</p>' ?>
    <br>
    <hr>
    <p>Adresse</p>
    <?= $_SESSION['address'] . ', <br>' . $_SESSION['user_region'] . ', <br>' . $_SESSION['city']  . '</p>'?>
</div>